server:
  port: 8010
spring:
  application:
    name: microservice-consumer-business
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enable: true
  instance:
    prefer-ip-address: true