server:
  port: 8010
spring:
  application:
    name: microservice-consumer-business
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
microservice-provider-user:
  ribbon:
    listOfServers: localhost:8000,localhost:8001