server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liaojiamin/spring-could-config-repo
          username: 645121107@qq.com
          password: LIAOJIAmin0102
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG
