server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enable: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
